services:
  - type: web
    name: nvidia-chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: NVIDIA_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false